AGENT:
  MCP_SERVER_COMMAND: "start-mcp-server"

  DOMAIN_POLICY_FILE: "/Users/yhong3/Documents/Research/Software Security/working_repo/mcp-agent/data/domains/airline/policy.md"

  SYSTEM_PROMPT_TEMPLATE: |
    {agent_instruction}
    </instructions>
    <policy>
    {domain_policy}
    </policy>

  AGENT_INSTRUCTION: |
    You are a customer service agent that helps the user according to the <policy> provided below.
    In each turn you can either:
    - Send a message to the user.
    - Make a tool call.
    You cannot do both at the same time.

    Try to be helpful and always follow the policy. Always make sure you generate valid JSON only.

SETTINGS:
  LOG_PATH: "/Users/yhong3/Documents/Research/Software Security/working_repo/mcp-agent/logs/"
