AGENT:
  MODEL: "gpt-4o"
  TEMPERATURE: 0.0

  MCP_SERVER_COMMAND: "start-mcp-server"

  INITIAL_CONVERSTION: "Hi! How can I help you today?"

  DOMAIN_POLICY_FILE: "/Users/yhong3/Documents/Research/Software Security/working_repo/mcp-agent/data/tau2/domains/airline/policy.md"

  SYSTEM_PROMPT_TEMPLATE: |
    {agent_instruction}
    </instructions>
    <policy>
    {domain_policy}
    </policy>

  AGENT_INSTRUCTION: |
    You are a customer service agent that helps the user according to the <policy> provided below.
    In each turn you can either:
    - Send a message to the user.
    - Make a tool call.
    You cannot do both at the same time.

    Try to be helpful and always follow the policy. Always make sure you generate valid JSON only.

USER:
  MODEL": "gpt-4o"
  TEMPERATURE: 1.0

  SYSTEM_PROMPT_TEMPLATE: |
    {global_user_sim_guidelines}

    <scenario>
    {instructions}
    </scenario>

  SIMULATION_GUIDELINE_PATH: "/Users/yhong3/Documents/Research/Software Security/working_repo/mcp-agent/data/tau2/user_simulator/simulation_guidelines.md"
  

SETTINGS:
  LOG_PATH: "/Users/yhong3/Documents/Research/Software Security/working_repo/mcp-agent/logs/agent/"
